security:
    enable_authenticator_manager: true
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'
    providers:
        app_users_provider:
            entity:
                class: App\Entity\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            lazy: true
            provider: app_users_provider
            access_denied_handler: App\Security\AccessDeniedHandler
            form_login:
                login_path: security_login
            custom_authenticators:
                - App\Security\Authenticator\FormAuthenticator
            logout:
                path: security_logout
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800 # 1 week in seconds
                path: /
    role_hierarchy:
        ROLE_PATIENT: [ROLE_PATIENT, ROLE_USER]
        ROLE_PSYCHOLOGIST: [ROLE_PSYCHOLOGIST, ROLE_USER]
        ROLE_ADMINISTRATOR: [ROLE_PSYCHOLOGIST, ROLE_ADMINISTRATOR]
    access_control:
        - { path: '^/admin', roles: ROLE_ADMINISTRATOR }