parameters:
    app.post_picture_directory: '%kernel.project_dir%/public/images/upload/post/'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $postUploadPath: '%app.post_picture_directory%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    App\Twig\AssetLoaderExtension:
        arguments:
            $environment: '%env(ASSET_ENV)%'
            $manifest: '%kernel.project_dir%/public/assets/manifest.json'
