parameters:
    app.post_picture_directory: '%kernel.project_dir%/public/images/upload/post/'

services:
    _defaults:
        autowire: true
        autoconfigure: true
        bind:
            string $postUploadPath: '%app.post_picture_directory%'

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
            - '../src/Tests/'

    App\Controller\:
        resource: '../src/Controller/'
        tags: [ 'controller.service_arguments' ]

    # Implementation
    Symfony\Component\Cache\Adapter\TagAwareAdapterInterface:
        class: Symfony\Component\Cache\Adapter\TagAwareAdapter
        arguments: ['@cache.app']

    # Subscribers
    App\EventListener\PostSubscriber:
        tags:
            - name: 'doctrine.event_subscriber'
              entity: 'App\Entity\User'

    # Twig
    App\Twig\AssetLoaderExtension:
        arguments:
            $environment: '%env(ASSET_ENV)%'
            $manifest: '%kernel.project_dir%/public/assets/manifest.json'